version: "3"

services:

  server-1:
    image: my-server
    container_name: my-server-1
    build: ./server
    restart: always
    ports:
      - 8001:8080
    environment:
      - SERVER_ID=1

  server-2:
    image: my-server
    container_name: my-server-2
    build: ./server
    restart: always
    ports:
      - 8002:8080
    environment:
      - SERVER_ID=2

  proxy:
    image: nginx:stable
    container_name: my-proxy
    restart: always
    network_mode: host
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
